-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 16:39:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema memorypond
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memorypond` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `memorypond` ;

-- -----------------------------------------------------
-- Table `memorypond`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `memorypond`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`question` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `weight` INT(11) NULL DEFAULT '100',
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `memorypond`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `memorypond`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(300) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'MEMBER',
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  `has_visited` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `memorypond`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `weight` INT(11) NULL DEFAULT '100',
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  `member_id` INT(11) NOT NULL,
  `question_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_post_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `memorypond`.`question` (`id`),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`member_id`)
    REFERENCES `memorypond`.`member` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `memorypond`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL DEFAULT NULL,
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  `member_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `memorypond`.`post` (`id`),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`member_id`)
    REFERENCES `memorypond`.`member` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `memorypond`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memorypond`.`like` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  `member_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_user1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_like_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `memorypond`.`post` (`id`),
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`member_id`)
    REFERENCES `memorypond`.`member` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
