spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/memorypond?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: memorypond
    password: memorypond

  flyway:
    locations: classpath:/db.migration
    enabled: false
    baseline-on-migrate: true